// Copyright 2024 Deepgram SDK contributors. All Rights Reserved.
// Use of this source code is governed by a MIT license that can be found in the LICENSE file.
// SPDX-License-Identifier: MIT

package interfacesv2

import (
	commoninterfaces "github.com/deepgram/deepgram-go-sdk/v3/pkg/client/common/v1/interfaces"
	clientinterfaces "github.com/deepgram/deepgram-go-sdk/v3/pkg/client/interfaces"
	clientinterfacesv2 "github.com/deepgram/deepgram-go-sdk/v3/pkg/client/interfaces/v2"
)

// MessageType is used to bootstrap unmarshalling of any incoming server message.
// All Flux server messages carry a "type" field.
type MessageType struct {
	Type string `json:"type"`
}

// -----------------------------------------------------------------------
// Server → Client responses
// -----------------------------------------------------------------------

// OpenResponse is the local WebSocket connection-opened event (generated by the SDK,
// not a Deepgram server message).
type OpenResponse = commoninterfaces.OpenResponse

// ConnectedResponse is the first message sent by the server immediately after the
// WebSocket handshake completes.
//
// JSON example:
//
//	{"type":"ListenV2Connected","request_id":"550e8400-e29b-41d4-a716-446655440000","sequence_id":"1"}
type ConnectedResponse struct {
	Type       string `json:"type"`
	RequestID  string `json:"request_id"`
	SequenceID int    `json:"sequence_id"`
}

// TurnWord is a single recognized word inside a TurnInfoResponse.
type TurnWord struct {
	Word       string  `json:"word"`
	Confidence float64 `json:"confidence"`
}

// TurnInfoResponse is streamed in real-time as speech is detected and turns are managed.
// Inspect EventType to understand which stage of the turn this message represents:
//   - "StartOfTurn"    — server detected the beginning of a new speech turn
//   - "Update"         — interim transcript update within the current turn
//   - "EagerEndOfTurn" — early end-of-turn signal (see eager_eot_threshold)
//   - "TurnResumed"    — speech resumed after EagerEndOfTurn; turn is not yet complete
//   - "EndOfTurn"      — final, complete transcript for the turn
type TurnInfoResponse struct {
	Type               string     `json:"type"`
	RequestID          string     `json:"request_id"`
	SequenceID         int        `json:"sequence_id"`
	EventType          string     `json:"event"`
	TurnIndex          int        `json:"turn_index"`
	AudioWindowStart   float64    `json:"audio_window_start,omitempty"`
	AudioWindowEnd     float64    `json:"audio_window_end,omitempty"`
	Transcript         string     `json:"transcript"`
	Words              []TurnWord `json:"words,omitempty"`
	EndOfTurnConfidence float64   `json:"end_of_turn_confidence,omitempty"`
	Languages          []string   `json:"languages,omitempty"`
	LanguagesHinted    []string   `json:"languages_hinted,omitempty"`
}

// ConfigureSuccessResponse acknowledges that a mid-session Configure message was accepted.
type ConfigureSuccessResponse struct {
	Type       string                        `json:"type"`
	RequestID  string                        `json:"request_id"`
	SequenceID int                           `json:"sequence_id"`
	Thresholds *clientinterfacesv2.FluxThresholds `json:"thresholds,omitempty"`
	Keyterms   []string                      `json:"keyterms,omitempty"`
}

// ConfigureFailureResponse signals that a mid-session Configure message was rejected.
type ConfigureFailureResponse struct {
	Type       string `json:"type"`
	RequestID  string `json:"request_id"`
	SequenceID int    `json:"sequence_id"`
}

// FatalErrorResponse is a terminal server error. The server will close the connection
// after sending this message. Wire type field value is "Error".
type FatalErrorResponse struct {
	Type        string `json:"type"`
	SequenceID  int    `json:"sequence_id"`
	Code        string `json:"code"`
	Description string `json:"description"`
}

// CloseResponse is the local WebSocket connection-closed event (generated by the SDK).
type CloseResponse = commoninterfaces.CloseResponse

// ErrorResponse is a Deepgram connection-level error.
type ErrorResponse = clientinterfaces.DeepgramError

// -----------------------------------------------------------------------
// Client → Server control messages (sent as JSON text frames)
// -----------------------------------------------------------------------

// ConfigureMessage is the JSON payload for a mid-session configuration update.
// Build via WSCallback.Configure() or WSChannel.Configure() — do not construct directly.
//
// JSON example:
//
//	{"type":"Configure","thresholds":{"eot_threshold":0.8},"keyterms":["Deepgram","Flux"]}
type ConfigureMessage struct {
	Type          string                             `json:"type"` // always "Configure"
	Thresholds    *clientinterfacesv2.FluxThresholds `json:"thresholds,omitempty"`
	Keyterms      []string                           `json:"keyterms,omitempty"`
	LanguageHints []string                           `json:"language_hints,omitempty"`
}
