// Copyright 2026 Deepgram SDK contributors. All Rights Reserved.
// Use of this source code is governed by a MIT license that can be found in the LICENSE file.
// SPDX-License-Identifier: MIT

package interfacesv2

import (
	commoninterfaces "github.com/deepgram/deepgram-go-sdk/v3/pkg/client/common/v1/interfaces"
	clientinterfaces "github.com/deepgram/deepgram-go-sdk/v3/pkg/client/interfaces"
)

// MessageType is used to bootstrap unmarshalling of any incoming server message.
// All Flux TTS server text messages carry a "type" field.
type MessageType struct {
	Type string `json:"type"`
}

// -----------------------------------------------------------------------
// Server → Client responses
// -----------------------------------------------------------------------

// OpenResponse is the local WebSocket connection-opened event (generated by the SDK,
// not a Deepgram server message).
type OpenResponse = commoninterfaces.OpenResponse

// ConnectedResponse is sent immediately on a successful connection. Successor to
// the /v1/speak Metadata message.
//
// JSON example:
//
//	{"type":"Connected","request_id":"550e8400-e29b-41d4-a716-446655440000","model_name":"flux-haley-en","model_version":"2026.06.01","model_uuids":["..."]}
type ConnectedResponse struct {
	Type         string   `json:"type"`
	RequestID    string   `json:"request_id"`
	ModelName    string   `json:"model_name"`
	ModelVersion string   `json:"model_version"`
	ModelUUIDs   []string `json:"model_uuids"`
}

// SpeechStartedResponse is emitted at the start of each new turn, before audio
// streaming begins. It carries the server-assigned speech_id that identifies the
// turn. Fires once per turn, not on internal auto-flush boundaries.
type SpeechStartedResponse struct {
	Type string `json:"type"`
	// SpeechID is the server-minted identifier for this turn, of the form
	// dg_sp_<12 hex digits>. Informational.
	SpeechID string `json:"speech_id"`
}

// ControlsApplied counts the inline controls the server acted on during a turn.
// Inline pause and pronunciation controls are not applied at launch, so every
// count is currently 0.
type ControlsApplied struct {
	PronunciationsApplied int `json:"pronunciations_applied"`
	BreaksApplied         int `json:"breaks_applied"`
	PronunciationWarnings int `json:"pronunciation_warnings"`
}

// SpeechMetadataResponse is emitted at turn boundaries (manual Flush), after all
// audio for the turn has been sent. Reports billing and timing for the completed turn.
type SpeechMetadataResponse struct {
	Type     string `json:"type"`
	SpeechID string `json:"speech_id"`
	// AudioDurationMs is the total audio duration produced for this turn, in milliseconds.
	AudioDurationMs int `json:"audio_duration_ms"`
	// InputCharacterCount is the raw input character count for this turn, before
	// text normalization.
	InputCharacterCount int `json:"input_character_count"`
	// BillableCharacterCount is the input character count with stripped control
	// characters removed. Always <= InputCharacterCount.
	BillableCharacterCount int             `json:"billable_character_count"`
	ControlsApplied        ControlsApplied `json:"controls_applied"`
}

// TurnMetadata is the per-turn billing/timing body nested inside
// SpeechInterruptedResponse.
type TurnMetadata struct {
	SpeechID               string          `json:"speech_id"`
	AudioDurationMs        int             `json:"audio_duration_ms"`
	InputCharacterCount    int             `json:"input_character_count"`
	BillableCharacterCount int             `json:"billable_character_count"`
	ControlsApplied        ControlsApplied `json:"controls_applied"`
}

// SpeechInterruptedResponse is sent in reply to an Interrupt, once synthesis has
// concluded and audio generation has stopped. Reports what the user heard, what
// they did not, and the billing and timing of the turn the interrupt landed in.
type SpeechInterruptedResponse struct {
	Type string `json:"type"`
	// AudioPlayedMs is how much audio the client had played when the interrupt
	// landed, in milliseconds from the start of the session. Echoes the Interrupt's
	// playback_offset when one was supplied; otherwise it is the server's own total.
	AudioPlayedMs int `json:"audio_played_ms"`
	// TextSpoken is the portion of the turn's text the user heard. Omitted when the
	// Interrupt carried no playback_offset.
	TextSpoken string `json:"text_spoken,omitempty"`
	// TextRemaining is the portion of the turn's text the user did not hear. Omitted
	// when the Interrupt carried no playback_offset.
	TextRemaining string       `json:"text_remaining,omitempty"`
	Metadata      TurnMetadata `json:"metadata"`
}

// FlushedResponse is emitted when the turn's buffer has actually been flushed —
// not an immediate receipt echo. When earlier turns are still synthesizing, the
// server holds the Flushed event behind them, so it can arrive well after the
// Flush was sent. It confirms buffer completion only; SpeechMetadata is the signal
// that all audio for the turn has been delivered. Not emitted for internal
// auto-flush boundaries.
type FlushedResponse struct {
	Type     string `json:"type"`
	SpeechID string `json:"speech_id"`
}

// SessionMetadataResponse is the final server message before the WebSocket closes.
// Reports cumulative session totals across all turns.
type SessionMetadataResponse struct {
	Type string `json:"type"`
	// TotalAudioDurationMs is the cumulative audio duration produced across the
	// session, in milliseconds. An Interrupt rebases this onto the audio the client
	// actually played.
	TotalAudioDurationMs        int `json:"total_audio_duration_ms"`
	TotalInputCharacterCount    int `json:"total_input_character_count"`
	TotalBillableCharacterCount int `json:"total_billable_character_count"`
}

// SpeakConfiguration is the synthesis configuration echoed in ConfigureSuccess.
// A field is present only when it has been set on this session.
type SpeakConfiguration struct {
	Speed float64 `json:"speed,omitempty"`
}

// ConfigureSuccessResponse is sent when a Configure was accepted and applied.
// Applied echoes the configuration now in effect; a Configure that named no field
// is answered with an empty applied object.
type ConfigureSuccessResponse struct {
	Type    string             `json:"type"`
	Applied SpeakConfiguration `json:"applied"`
}

// ConfigureFailureResponse is sent when a Configure was rejected. The stream is
// unaffected and the previous configuration stays in force.
type ConfigureFailureResponse struct {
	Type string `json:"type"`
	// Code is the failure code in SCREAMING_SNAKE_CASE: SPEED_OUT_OF_RANGE,
	// SPEED_INCREMENT_INVALID, SPEED_NOT_SUPPORTED, or INTERNAL_ERROR.
	Code string `json:"code"`
	// Field names the configuration field the failure is about. Absent when the
	// failure is not tied to one field.
	Field string `json:"field,omitempty"`
	// Value echoes the rejected value for Field. Absent when there is no offending
	// value to echo.
	Value       float64 `json:"value,omitempty"`
	Description string  `json:"description"`
}

// WarningResponse is an informational message; synthesis continues and the
// connection is unaffected. See the API docs for the warning code catalog
// (e.g. NO_ACTIVE_SPEECH, NO_SYNTHESIZABLE_TEXT, SYNTHESIS_RETRYING,
// NO_AUDIO_GENERATED, INTERRUPT_IN_PROGRESS, INVALID_INTERRUPT_OFFSET).
type WarningResponse struct {
	Type        string `json:"type"`
	Code        string `json:"code"`
	Description string `json:"description"`
}

// FatalErrorResponse is a fatal, server-originated error, always followed by a
// WebSocket close. Codes use Deepgram's DOMAIN-NNNN convention (e.g. MESSAGE-0000,
// NET-0000). Wire type field value is "Error".
type FatalErrorResponse struct {
	Type        string `json:"type"`
	Code        string `json:"code"`
	Description string `json:"description"`
}

// CloseResponse is the local WebSocket connection-closed event (generated by the SDK).
type CloseResponse = commoninterfaces.CloseResponse

// ErrorResponse is a Deepgram connection-level error.
type ErrorResponse = clientinterfaces.DeepgramError

// -----------------------------------------------------------------------
// Client → Server control messages (sent as JSON text frames)
// -----------------------------------------------------------------------

// SpeakMessage sends text to be synthesized into the active turn. Build via
// WSCallback.Speak() or WSChannel.Speak() — do not construct directly. The server
// applies light normalization and preprocessing before synthesis, tracks the
// active turn internally, and assigns a speech_id; clients do not specify one.
//
// JSON example:
//
//	{"type":"Speak","text":"Sure, I can help you cancel your subscription."}
type SpeakMessage struct {
	Type string `json:"type"` // always "Speak"
	Text string `json:"text"`
}

// FlushMessage ends the active turn. The server drains the buffer, generates the
// remaining audio, and reports the turn with a SpeechMetadata event.
//
// JSON example:
//
//	{"type":"Flush"}
type FlushMessage struct {
	Type string `json:"type"` // always "Flush"
}

// PlaybackOffset reports how much audio the client had played when the user
// barged in. Optional on Interrupt: without it the server cannot split the
// turn's text, so SpeechInterrupted omits text_spoken and text_remaining.
// The offset is cumulative from the start of the session, not the current turn;
// each Interrupt must advance past the position the previous one established.
type PlaybackOffset struct {
	// Type is the offset unit; "time_ms" is the only supported form.
	Type string `json:"type"`
	// Value is milliseconds of session audio the client played before barging in.
	Value int `json:"value"`
}

// InterruptMessage reports that the user barged in. The server stops active audio
// generation, discards any buffered text pending generation, and replies with
// SpeechInterrupted once the model confirms the canceled turn has drained.
//
// JSON example:
//
//	{"type":"Interrupt","playback_offset":{"type":"time_ms","value":2340}}
type InterruptMessage struct {
	Type           string          `json:"type"` // always "Interrupt"
	PlaybackOffset *PlaybackOffset `json:"playback_offset,omitempty"`
}

// ConfigureMessage updates synthesis configuration mid-session without
// reconnecting. Build via WSCallback.Configure() or WSChannel.Configure().
// Speed is a pointer so an explicit value is distinguishable from "leave
// unchanged": nil omits the field, while a set value — including an invalid 0 —
// is serialized and validated rather than silently dropped by omitempty.
//
// JSON example:
//
//	{"type":"Configure","speed":1.05}
type ConfigureMessage struct {
	Type  string   `json:"type"` // always "Configure"
	Speed *float64 `json:"speed,omitempty"`
}

// CloseMessage gracefully closes the connection. The server drains all remaining
// audio (the active turn plus any turns still queued behind it), emits a final
// SessionMetadata, then closes the socket.
//
// JSON example:
//
//	{"type":"Close"}
type CloseMessage struct {
	Type string `json:"type"` // always "Close"
}
