name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  test:
    name: Go Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.19"

      - name: Verify dependencies
        run: |
          go mod download
          go mod verify

      - name: Run tests
        run: go test -v -run Test_ ./...

  release-please:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Create release PR or GitHub release
        uses: googleapis/release-please-action@v4
        id: release
        with:
          config-file: .github/release-please-config.json
          manifest-file: .github/.release-please-manifest.json
          target-branch: ${{ github.ref_name }}
